/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.UUID;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SpinnerDateModel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

import domain.Employee;
import domain.Person;
import domain.Role;
import service.ImageService;
import service.impl.EmployeeServiceImpl;
import service.impl.PersonServiceImpl;
import service.impl.RoleServiceImpl;
import utils.ImageUtil;

/**
 *
 * @author Administrator
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textSubName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdbtnNam = new javax.swing.JRadioButton();
        rdbtnNam.setSelected(true);
        buttonGroup.add(rdbtnNam);
        rdbtnNam.setFont(new Font("Tahoma", Font.PLAIN, 12));
        rdbtnNu = new javax.swing.JRadioButton();
        buttonGroup.add(rdbtnNu);
        rdbtnNu.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jLabel7 = new javax.swing.JLabel();
        textUserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textSDT = new javax.swing.JTextField();
        lblAvata = new javax.swing.JLabel();
        lblAvata.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        textSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		table.setModel(new DefaultTableModel(
			new Object[][] {
				{null, null, null, null, null},
			},
			new String[] {
				"H\u1ECD v\u00E0 T\u00EAn", "SDT", "Email", "Ng\u00E0y sinh", "\u0110\u1ECBa ch\u1EC9"
			}
		) {
			boolean[] columnEditables = new boolean[] {
				false, false, false, false, false
			};
			public boolean isCellEditable(int row, int column) {
				return columnEditables[column];
			}
		});
		table.getColumnModel().getColumn(4).setPreferredWidth(165);
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jLabel2.setText("Id: ");

        jLabel4.setText("Họ và Tên đệm");

        jLabel5.setText("Tên");

        jLabel6.setText("Gioi Tinh: ");

        rdbtnNam.setText("Nam");

        rdbtnNu.setText("Nữ");

        jLabel7.setText("UseName: ");

        jLabel8.setText("Mật khẩu");

        jLabel9.setText("Số điện thoại");

        lblAvata.setForeground(new java.awt.Color(255, 255, 102));
        
        lblID = new JLabel();
        lblID.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        JButton btnChoseAvate = new JButton();
        btnChoseAvate.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		choseAvate();
        	}
        });
        btnChoseAvate.setText("ADD");
        
        JButton btnRemoveAvata = new JButton();
        btnRemoveAvata.setText("ADD");
        
        pwMatKhau = new JPasswordField();
        
        lblNgySinh = new JLabel();
        lblNgySinh.setText("Ngày sinh");
        
        spinnerDate = new JSpinner();
        spinnerDate.setModel(new SpinnerDateModel(new Date(1668531600000L), null, null, Calendar.DAY_OF_YEAR));
        
        lblEmail = new JLabel();
        lblEmail.setText("Email");
        
        textEmail = new JTextField();
        
        lblaCh = new JLabel();
        lblaCh.setText("Địa chỉ");
        
        textDiaChi = new JTextArea();
        
        JButton btnAdd = new JButton();
        btnAdd.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnAddNhanVien();
        	}
        });
        btnAdd.setText("ADD");
        
        JButton btnUpdate = new JButton();
        btnUpdate.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnUpdateActionPerformed();
        	}
        });
        btnUpdate.setText("Update");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(lblAvata, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnChoseAvate, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnRemoveAvata, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        					.addGap(86))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel5)
        								.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        							.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(jPanel3Layout.createSequentialGroup()
        									.addGap(10)
        									.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(textSubName, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        										.addComponent(textName, 341, 341, Short.MAX_VALUE)
        										.addGroup(jPanel3Layout.createSequentialGroup()
        											.addPreferredGap(ComponentPlacement.UNRELATED)
        											.addComponent(textUserName, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))))
        								.addGroup(jPanel3Layout.createSequentialGroup()
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(lblID, GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(49)
        							.addComponent(rdbtnNam)
        							.addGap(27)
        							.addComponent(rdbtnNu))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel3Layout.createSequentialGroup()
        									.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        									.addGap(18))
        								.addGroup(jPanel3Layout.createSequentialGroup()
        									.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        									.addGap(29)))
        							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(pwMatKhau, GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        								.addComponent(textSDT, 339, 339, 339)))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(lblNgySinh, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(spinnerDate, GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(lblEmail, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(textEmail, GroupLayout.PREFERRED_SIZE, 339, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(lblaCh, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel3Layout.createSequentialGroup()
        									.addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        									.addGap(28)
        									.addComponent(btnUpdate, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE))
        								.addComponent(textDiaChi, GroupLayout.PREFERRED_SIZE, 339, GroupLayout.PREFERRED_SIZE))))
        					.addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGap(77)
        					.addComponent(btnChoseAvate, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(btnRemoveAvata, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblAvata, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        					.addGap(27)))
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel2)
        				.addComponent(lblID, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(textSubName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(textName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 11, GroupLayout.PREFERRED_SIZE)
        				.addComponent(rdbtnNam)
        				.addComponent(rdbtnNu))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textUserName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel7))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(pwMatKhau, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textSDT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel9))
        			.addGap(21)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNgySinh)
        				.addComponent(spinnerDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblEmail))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblaCh)
        				.addComponent(textDiaChi, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnAdd)
        				.addComponent(btnUpdate))
        			.addGap(20))
        );
        jPanel3.setLayout(jPanel3Layout);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel14.setText("Tên Khách Hàng");

        btnSearch.setText("Tìm ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addComponent(jLabel14)
        			.addPreferredGap(ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        			.addComponent(textSearch, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnSearch, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel14)
        				.addComponent(textSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnSearch))
        			.addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel5.setLayout(jPanel5Layout);

        
        jScrollPane1.setViewportView(table);

        jButton12.setText("Nhân Viên Hiện Tại");

        jButton11.setText("Khôi Phục Nhân Viên");

        jButton13.setText("Nhân Viên Đã Xóa");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jLabel1 = new javax.swing.JLabel();
        
                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setText("Thông Tin Nhân Viên");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(73)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jButton12, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton11))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton13))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(101)
        					.addComponent(jLabel1))
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 408, GroupLayout.PREFERRED_SIZE)
        			.addGap(2)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(33)
        					.addComponent(jButton12)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton11))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(56)
        					.addComponent(jButton13)))
        			.addContainerGap())
        );
        jPanel4.setLayout(jPanel4Layout);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        			.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 589, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(31, 52, Short.MAX_VALUE))
        				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 649, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 962, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 722, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed() {
    	Employee employee =  getFormData();
		if (employee!=null) {
			try {
				String id = lblID.getText();
				employee.setId(UUID.fromString(id));
				new EmployeeServiceImpl().update(employee);
				JOptionPane.showMessageDialog(this, "Thành công");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "lôi");
			}
		}
	}

	private void choseAvate() {

		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setFileFilter(new FileFilter() {
			@Override
			public String getDescription() {
				return "Images file (.jpg)";
			}

			@Override
			public boolean accept(File f) {
				if (f.isDirectory()) {
					return true;
				} else {
					return f.getName().toLowerCase().endsWith(".jpg");
				}
			}
		});
		if (fileChooser.showDialog(this, "Chọn file") == fileChooser.APPROVE_OPTION) {
			File file = fileChooser.getSelectedFile();
			if (file.exists()) {
				ImageIcon icon = new ImageIcon(file.getPath());
				Image image = ImageUtil.resize(icon.getImage(), 130, 143);
				ImageIcon imageIcon = new ImageIcon(image);
//				try {
//					pertionImage = ImageService.toByteArray(icon.getImage(), "jpg");
//				} catch (IOException e1) {
//					e1.printStackTrace();
//				}
				lblAvata.setIcon(imageIcon);
			} else {
				JOptionPane.showMessageDialog(this, "File không tồn tại");
			}
		} else {
			return;
		}

	
		
	}

	private void btnAddNhanVien() {
		Employee employee =  getFormData();
		if (employee!=null) {
			try {
				new EmployeeServiceImpl().insert(employee);
				JOptionPane.showMessageDialog(this, "Thành công");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "lôi");
			}
		}
	}

	private Employee getFormData() {
		Employee employee = new Employee();
		Person person = new Person();
		String subName = textSubName.getText();
		person.setSurName(subName);
		String name = textName.getText();
		person.setName(name);
		Boolean gioiTinh = rdbtnNam.isSelected();
		person.setGender(gioiTinh);
		String sdt = textSDT.getText();
		person.setPhoneNumber(sdt);
		Date ngaySinh = (Date) spinnerDate.getValue();
		person.setDateOfBirth(ngaySinh);
		String email = textEmail.getText();
		person.setEmail(email);
		String diaChi = textDiaChi.getText();
		person.setAddress(diaChi);
		String userNmae = textUserName.getText();
		String password = pwMatKhau.getText();
		employee.setPerson(person);
		
		employee.setUsername(userNmae);
		employee.setPassword(password);
		RoleServiceImpl roleServiceImpl = new RoleServiceImpl();
		roleServiceImpl.findAll().get(0).getId();
		employee.setRole(roleServiceImpl.findAll().get(0));
		return employee;
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvata;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rdbtnNam;
    private javax.swing.JRadioButton rdbtnNu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField textSubName;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textUserName;
    private javax.swing.JTextField textSDT;
    private javax.swing.JTextField textSearch;
    private JPasswordField pwMatKhau;
    private final ButtonGroup buttonGroup = new ButtonGroup();
    private JLabel lblNgySinh;
    private JLabel lblEmail;
    private JTextField textEmail;
    private JLabel lblaCh;
    private JTextArea textDiaChi;
    private JSpinner spinnerDate;
    private JLabel lblID;
}
